const API='/.netlify/functions/api';
let state={me:null,members:[],rules:[],announcements:[],stats:{}};
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const go=x=>location.hash=x;
async function api(action,data={}){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({action,...data})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Request failed');return j;}
async function load(){try{state.me=(await api('me')).profile}catch{state.me=null}}
function logout(){api('logout').finally(()=>{state.me=null;go('home')})}
function adm(){return ['Moderator','GC Admin','Website Head'].includes(state.me?.role)}
function head(){return state.me?.role==='Website Head'}
function shell(c){const u=state.me;return `<div class="bg"></div><div class="watermark">M<br>A<br>D<br>E<br><br>B<br>Y<br><br>S<br>A<br>M<br>A<br>R<br>T<br>H</div><div class="wrap"><nav class="nav"><b>🌑 Shadow Army</b><div class="links"><button onclick="go('home')">Home</button>${u?`<button onclick="go('dashboard')">Dashboard</button><button onclick="go('profile')">My Profile</button><button onclick="go('members')">Members</button><button onclick="go('rules')">Rules</button><button onclick="go('announcements')">Announcements</button><button onclick="go('stats')">Community Stats</button><button onclick="go('settings')">Settings</button>${adm()?`<button onclick="go('admin')">Admin Panel</button>`:''}${head()?`<button onclick="go('head')">Head Panel</button>`:''}<button onclick="logout()">Logout</button>`:`<button onclick="go('login')">Login</button><button onclick="go('register')">Register</button>`}</div></nav>${c}<div class="footer">Developed by Samarth</div></div>`}
function card(x){return `<div class="card">${x}</div>`}
function stat(a,b){return card(`<div class="muted">${a}</div><h2>${b}</h2>`)}
async function render(){await load();let p=location.hash.slice(1)||'home';if(['dashboard','profile','members','rules','announcements','stats','settings','admin','head'].includes(p)&&!state.me){go('login');return}if(p==='admin'&&!adm()){go('dashboard');return}if(p==='head'&&!head()){go('dashboard');return}let c='';
if(p==='home')c=`<section class="hero">${card(`<div class="muted">COMMUNITY PORTAL</div><h1>🌑 Shadow Army</h1><h2>More Than Just a GC</h2><p class="muted">Cute • Aesthetic • Community</p><button class="btn" onclick="go('${state.me?'dashboard':'register'}')">${state.me?'Open Dashboard':'Join Shadow Army'}</button>`)}</section>`;
if(p==='login')c=`<section class="hero">${card(`<h2>Welcome back 🌑</h2><input id="lu" class="input" placeholder="Username"><input id="lp" type="password" class="input" placeholder="Password"><button class="btn" onclick="login()">Login</button><p id="msg"></p>`)}</section>`;
if(p==='register')c=`<section class="hero">${card(`<h2>Create Account ✨</h2><input id="rn" class="input" placeholder="Full Name *"><input id="ru" class="input" placeholder="Username *"><input id="rclass" class="input" placeholder="Class"><input id="rage" type="number" class="input" placeholder="Age"><input id="rcity" class="input" placeholder="From / City"><input id="rhobby" class="input" placeholder="Hobby"><textarea id="rbio" class="input" placeholder="Bio"></textarea><input id="rp" type="password" class="input" placeholder="Password *"><input id="rc" type="password" class="input" placeholder="Confirm Password *"><button class="btn" onclick="register()">Create Account</button><p id="msg"></p>`)}</section>`;
if(p==='dashboard'){const s=state.stats=await api('stats').then(x=>x.stats);c=`<section class="hero">${card(`<h1>Hey, ${esc(state.me.name)} 👋</h1><p>Welcome to your full Shadow Army dashboard.</p><span class="pill">${esc(state.me.role)}</span>`)}</section><div class="grid">${stat('Total Members',s.members)}${stat('Admins',s.admins)}${stat('Rules',s.rules)}${stat('Announcements',s.announcements)}</div>`}
if(p==='profile')c=`<section class="hero">${card(`<h2>My Profile</h2><h3>${esc(state.me.name)} · @${esc(state.me.username)}</h3><p>Class ${esc(state.me.class)} · Age ${esc(state.me.age)}</p><p>From ${esc(state.me.city)} · Hobby ${esc(state.me.hobby)}</p><p>${esc(state.me.bio)}</p><span class="pill">${esc(state.me.role)}</span><p>Joined ${new Date(state.me.created_at).toLocaleDateString()}</p><button class="btn" onclick="editProfile()">Edit Profile</button>`)}</section>`;
if(p==='members'){const x=await api('members');state.members=x.members;c=`<section class="hero">${card(`<h2>Members 🌑</h2><input id="q" class="input" placeholder="Search members" oninput="draw()">`)}</section><div id="mg" class="grid"></div>`}
if(p==='rules'){state.rules=(await api('rules')).rules;c=`<section class="hero">${card(`<h2>Community Rules</h2>${state.rules.map((x,i)=>`<p>${i+1}. ${esc(x.rule_text)}</p>`).join('')}${adm()?`<button class="btn" onclick="addRule()">Add Rule</button>`:''}`)}</section>`}
if(p==='announcements'){state.announcements=(await api('announcements')).announcements;c=`<section class="hero">${card(`<h2>Announcements 📢</h2>${state.announcements.map(x=>`<article class="card"><h3>${esc(x.title)}</h3><p>${esc(x.description)}</p><small>${new Date(x.created_at).toLocaleString()}</small></article>`).join('')}${adm()?`<button class="btn" onclick="addAnn()">New Announcement</button>`:''}`)}</section>`}
if(p==='stats'){const s=await api('stats');state.stats=s.stats;c=`<section class="hero">${card(`<h2>Community Stats 📊</h2><div class="grid">${stat('Members',s.stats.members)}${stat('VIP',s.stats.vip)}${stat('OG',s.stats.og)}${stat('Admins',s.stats.admins)}${stat('Rules',s.stats.rules)}${stat('Announcements',s.stats.announcements)}</div>`)}</section>`}
if(p==='settings')c=`<section class="hero">${card(`<h2>Settings ⚙️</h2><button class="btn" onclick="document.body.classList.toggle('light')">Dark / Light</button> <button class="btn" onclick="logout()">Logout</button>`)}</section>`;
if(p==='admin'){const x=await api('members');state.members=x.members;c=`<section class="hero">${card(`<h2>Admin Panel 🛡️</h2><p>Admins manage community content. Website Head manages roles.</p>`)}</section><div class="grid">${state.members.map(x=>card(`<h3>${esc(x.name)}</h3><p>@${esc(x.username)}</p><span class="pill">${esc(x.role)}</span>${head()&&x.role!=='Website Head'?`<br><br><button class="btn" onclick="role('${esc(x.username)}')">Change Role</button>`:''}`)).join('')}</div>`}
if(p==='head')c=`<section class="hero">${card(`<h2>Website Head Panel 👑</h2><p>Highest permissions. Add/promote administrators anytime.</p><button class="btn" onclick="promote()">Add / Promote Administrator</button>`)}</section>`;
document.getElementById('app').innerHTML=shell(c);if(p==='members')draw()}
function draw(){const q=(document.getElementById('q')?.value||'').toLowerCase();document.getElementById('mg').innerHTML=state.members.filter(x=>(x.name+' '+x.username+' '+x.role+' '+x.city).toLowerCase().includes(q)).map(x=>card(`<h3>${esc(x.name)}</h3><p>@${esc(x.username)}</p><span class="pill">${esc(x.role)}</span><p>Class ${esc(x.class)} · ${esc(x.city)}</p><p>${esc(x.hobby)}</p><p>${esc(x.bio)}</p>`)).join('')}
async function login(){try{const x=await api('login',{username:lu.value,password:lp.value});state.me=x.profile;go('dashboard')}catch(e){msg.textContent=e.message}}
async function register(){try{const x=await api('register',{name:rn.value,username:ru.value,class:rclass.value,age:rage.value,city:rcity.value,hobby:rhobby.value,bio:rbio.value,password:rp.value,confirmPassword:rc.value});state.me=x.profile;go('dashboard')}catch(e){msg.textContent=e.message}}
async function editProfile(){const name=prompt('Name',state.me.name);if(name===null)return;const hobby=prompt('Hobby',state.me.hobby)||'';const bio=prompt('Bio',state.me.bio)||'';state.me=(await api('profile_update',{name,hobby,bio})).profile;render()}
async function addRule(){const rule=prompt('New rule');if(rule){await api('add_rule',{rule});render()}}
async function addAnn(){const title=prompt('Title'),description=prompt('Description');if(title&&description){await api('add_announcement',{title,description});render()}}
async function role(username){const r=prompt('Role: Member, VIP Member, OG Member, Moderator, GC Admin');if(['Member','VIP Member','OG Member','Moderator','GC Admin'].includes(r)){await api('change_role',{username,role:r});render()}}
async function promote(){const username=prompt('Existing username'),role=prompt('GC Admin or Moderator');if(['GC Admin','Moderator'].includes(role)){await api('change_role',{username,role});render()}}
window.addEventListener('hashchange',render);render();
