-- 🌑 SHADOW ARMY — CUSTOM USERNAME/PASSWORD AUTH DATABASE
-- Run this once in Supabase SQL Editor.

-- 1) Existing profiles table: remove the Supabase Auth dependency because
-- this project intentionally uses username + password, with NO email/phone.
ALTER TABLE public.profiles
  ALTER COLUMN id SET DEFAULT gen_random_uuid();

DO $$
DECLARE c text;
BEGIN
  SELECT conname INTO c
  FROM pg_constraint
  WHERE conrelid = 'public.profiles'::regclass
    AND confrelid = 'auth.users'::regclass
  LIMIT 1;
  IF c IS NOT NULL THEN
    EXECUTE format('ALTER TABLE public.profiles DROP CONSTRAINT %I', c);
  END IF;
END $$;

-- 2) Secure password store. Passwords are NEVER stored in profiles.
CREATE TABLE IF NOT EXISTS public.auth_accounts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id uuid UNIQUE NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  username text UNIQUE NOT NULL,
  password_hash text NOT NULL,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE public.auth_accounts ENABLE ROW LEVEL SECURITY;

-- Only the Netlify server uses this table with the Supabase service-role key.
-- No browser policy is granted.

-- 3) Existing community tables
CREATE TABLE IF NOT EXISTS public.rules (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule_text text NOT NULL,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE public.rules ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.announcements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  description text NOT NULL,
  author_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;

-- 4) Allowed roles
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid='public.profiles'::regclass AND conname='profiles_role_check'
  ) THEN
    ALTER TABLE public.profiles ADD CONSTRAINT profiles_role_check CHECK (
      role IN ('Member','VIP Member','OG Member','Moderator','GC Admin','Website Head')
    );
  END IF;
END $$;

-- 5) Default rules
INSERT INTO public.rules (rule_text) SELECT 'Respect every member.'
WHERE NOT EXISTS (SELECT 1 FROM public.rules WHERE rule_text='Respect every member.');
INSERT INTO public.rules (rule_text) SELECT 'No unnecessary fights.'
WHERE NOT EXISTS (SELECT 1 FROM public.rules WHERE rule_text='No unnecessary fights.');
INSERT INTO public.rules (rule_text) SELECT 'Keep private conversations private.'
WHERE NOT EXISTS (SELECT 1 FROM public.rules WHERE rule_text='Keep private conversations private.');
INSERT INTO public.rules (rule_text) SELECT 'Don’t spam.'
WHERE NOT EXISTS (SELECT 1 FROM public.rules WHERE rule_text='Don’t spam.');
INSERT INTO public.rules (rule_text) SELECT 'Have fun and keep Shadow Army united. 🌑'
WHERE NOT EXISTS (SELECT 1 FROM public.rules WHERE rule_text='Have fun and keep Shadow Army united. 🌑');

-- 6) Public read policies. Writes are handled by the Netlify server.
DROP POLICY IF EXISTS "Anyone can view profiles" ON public.profiles;
CREATE POLICY "Anyone can view profiles" ON public.profiles FOR SELECT USING (true);

DROP POLICY IF EXISTS "Anyone can view rules" ON public.rules;
CREATE POLICY "Anyone can view rules" ON public.rules FOR SELECT USING (true);

DROP POLICY IF EXISTS "Anyone can view announcements" ON public.announcements;
CREATE POLICY "Anyone can view announcements" ON public.announcements FOR SELECT USING (true);

-- 7) Prevent browser access to password hashes even if policies are changed later.
REVOKE ALL ON public.auth_accounts FROM anon, authenticated;

-- 8) Verify with:
-- SELECT table_name FROM information_schema.tables
-- WHERE table_schema='public'
-- ORDER BY table_name;
